# azure.yaml - Azure Developer CLI configuration for AI Avatar
name: ai-avatar
metadata:
  template: ai-avatar@0.0.1-beta
services:
  web:
    project: ./src
    language: python
    host: containerapp
    env:
      AZURE_SPEECH_KEY: ${AZURE_SPEECH_KEY}
      AZURE_SPEECH_REGION: ${AZURE_SPEECH_REGION}
      FLASK_ENV: production
infra:
  provider: bicep
  path: ./infra
pipeline:
  provider: github
