name: ai-avatar
metadata:
  template: ai-avatar-containerapp@0.1.0

services:
  web:
    project: .
    language: python
    host: containerapp
    docker:
      path: ./Dockerfile
      context: .

hooks:
  predeploy:
    windows:
      shell: pwsh
      run: |
        Write-Host "Running pre-deployment tasks..."
        if (Test-Path requirements.txt) {
          pip install -r requirements.txt
        }
        Write-Host "Skipping UI tests during deployment"
    posix:
      shell: sh
      run: |
        echo "Running pre-deployment tasks..."
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        echo "Skipping UI tests during deployment"

infra:
  provider: bicep
  path: ./infra

pipeline:
  provider: github
